### ISSUE TITLE
hullo.dev security issue

### ISSUE THREAD

**Issue by andymans** [arturkulig/hullo#1]
Heads up - on Safari, FF, and Chrome attempting to reach hullo.dev throws up a security warning, blocking access to the docs site. Might be worth fixing this.

**Comment by arturkulig** [comment]
Thank you!
It seems that gitbook.com (docs host) has some problems and fixing those right now won't be possible. I have sent a request for help with the issue. I myself didn't notice it as their docs editor works just fine :)

Thank you for taking your time to notify me about this! I'll keep this github-issue open until the situation is resolved.
